# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9282b394c85bfb8f400ed73d227d2a3d2275674790679fe996d5e255cff2ed9a5b3b2977f259ed8d978400eaec5837ee0b5f61bbbf9ee7f5582174d881e9d89d

test:
  secret_key_base: 46b182272c3081eddb5578d520406b9cf37ff9e9a75256b32c5e53740f5d5cf7b849ccba27e31507ebf3e77313a24963ff485146fe1f861377871b1f5bbdeef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
